[project]
name = "trijectory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hatchling>=1.27.0",
    "lite-dist2>=0.1.3",
    "numpy>=2.2.6",
    "tqdm>=4.67.1",
]

[project.scripts]
post-query = "trijectory.post_study:main"
start-worker = "trijectory.start_worker:main"

[tool.hatch.build.targets.wheel]
packages = ["src/trijectory"]

[dependency-groups]
dev = [
    "matplotlib>=3.10.3",
    "pytest>=8.3.5",
    "ruff>=0.11.12",
    "ty>=0.0.1a8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
