target-version = "py313"
line-length = 119

[lint]
select = ["ALL"]
ignore = [
    "D",
    "FIX002",
    "ERA001",
    "FBT001",
    "FBT002",
    "EM101",
    "TRY003",
]

[lint.per-file-ignores]
"__init__.py" = [
    "F401"      # The imported class is rarely used within __init__.py
]
"tests/**.py" = [
    "S101",     # pytest use assert
    "PLR2004",  # use magic number
]

[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false